### ISSUE TITLE
nvim 0.8  deprecated  vim.lsp.buf.formatting_seq_sync

### ISSUE THREAD

**Issue by sukoi26** [Ultra-Code/awesome-neovim#1]
Deprecates the existing vim.lsp.buf.formatting function.
With this, vim.lsp.buf.format will replace all three:

    vim.lsp.buf.formatting
    vim.lsp.buf.formatting_sync
    vim.lsp.buf.formatting_seq_sync

 Use vim.lsp.buf.format { async = true } instead

**Comment by bernardassan** [comment]
@sukoi26 this is fixed in the latest master branch
